-- 新增支出表的額外欄位
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS payment_request BOOLEAN DEFAULT FALSE;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS ad_platform VARCHAR(50);
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS card_fee DECIMAL(12,2);
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS overseas_tax DECIMAL(12,2);
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS business_tax DECIMAL(12,2);
